# Generated by Django 5.2 on 2025-04-19 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('osm_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
